[package]
name = "vulkanrs"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = {version = "0.30.12", features = ["rwh_06"]}
raw-window-handle = "0.6.2"
thiserror = "2.0.12"

[build-dependencies]
shaderc = "0.9.1"