comment_width = 100
format_code_in_doc_comments = true
wrap_comments = true
unstable_features = true
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Mixed"